Updated to skia m133 builds

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,132 +8,132 @@ env:
   version: 1.1.2
 
 jobs:
-  mingw:
-   strategy:
-     fail-fast: false
-     matrix:
-       sys: [ucrt64]  # clang64,
-   name: ${{ matrix.sys }}
-   runs-on: windows-latest
-   defaults:
-     run:
-       shell: msys2 {0}
-   steps:
-     - uses: actions/checkout@v3
-     - uses: msys2/setup-msys2@v2
-       with:
-         msystem: ${{ matrix.sys }}
-         update: true
-         install: make
-         pacboy: toolchain:p glfw:p skia:p htslib:p freeglut:p glew:p ncurses:p fontconfig:p dlfcn:p libpng:p
-     - name: build
-       run: |
-         make
-     - name: upload
-       uses: actions/upload-artifact@v3
-       with:
-         name: mingw-${{ matrix.sys }}
-         path: ${{ github.workspace }}/*.exe
+  #  mingw:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       sys: [ucrt64]  # clang64,
+  #   name: ${{ matrix.sys }}
+  #   runs-on: windows-latest
+  #   defaults:
+  #     run:
+  #       shell: msys2 {0}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: msys2/setup-msys2@v2
+  #       with:
+  #         msystem: ${{ matrix.sys }}
+  #         update: true
+  #         install: make
+  #         pacboy: toolchain:p glfw:p skia:p htslib:p freeglut:p glew:p ncurses:p fontconfig:p dlfcn:p libpng:p
+  #     - name: build
+  #       run: |
+  #         make
+  #     - name: upload
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: mingw-${{ matrix.sys }}
+  #         path: ${{ github.workspace }}/*.exe
 
-  macos-package:
-
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ macos-14 ]  # macos-12,
-        include:
-          - os: macos-14
-            arch: intel
-          - os: macos-14
-            arch: m1
-
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Install dependencies
-        run: |
-          brew install imagemagick graphicsmagick dylibbundler glfw fontconfig
-          brew list | grep python@
-
-          /opt/homebrew/opt/python@3.13/bin/python3.13 -m venv py_venv
-          source py_venv/bin/activate
-
-          python -m pip install --upgrade pip
-          python -m pip install packaging
-
-          npm install --global create-dmg
-
-          which python && python --version
-          which python3 && python3 --version
-
-      - name: Build and install htslib with libdeflate
-        run: |
-          
-          wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.20/htslib-1.20.tar.bz2
-          tar -xvf htslib.tar.bz2 && mv htslib-* htslib && rm htslib.tar.bz2
-          
-          git clone --depth 1 https://github.com/ebiggers/libdeflate.git
-          cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build
-          cp build/libdeflate.a ../htslib
-          cp libdeflate.h ../htslib
-          ls ../htslib
-
-          cd ../htslib
-          LDFLAGS="$LDFLAGS -L./" CPPFLAGS="$CPPFLAGS -I./" ./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
-          make
-          sudo make install
-
-      - name: Make Prep
-        run: |
-          make prep
-
-      - name: package
-        run: |
-          
-          osacompile -o gw.app deps/gw_applescript_prog.txt
-          cp deps/gw_droplet.icns gw.app/Contents/Resources/droplet.icns
-          
-          echo "BUILDING GW"
-          
-          brew_lib=$(brew --prefix)/lib
-          brew_include=$(brew --prefix)/include
-          brew_bin=$(brew --prefix)/bin
-          
-          LDFLAGS="${LDFLAGS} -L${brew_lib}" CPPFLAGS="${CPPFLAGS} -I${brew_include}" make
-          
-          mv gw ./gw.app/Contents/MacOS
-          rm -rf include lib src Makefile
-          
-          PATH="$PATH:$brew_bin" dylibbundler -od -b -x ./gw.app/Contents/MacOS/gw -d ./gw.app/Contents/libs/ -p @executable_path/../libs/
-          
-          echo "VALIDATION"
-          otool -L gw.app/Contents/MacOS/gw
-          echo ""
-          
-          echo "CODE SIGNING"
-          ls -l
-          sudo chown -R $(whoami) ./gw.app
-          chmod -R a+rw ./gw.app
-          sudo codesign --remove-signature ./gw.app
-          sudo codesign --force --deep -s - gw.app -v
-          sudo codesign --verify -vvvv gw.app
-          
-          PATH="$PATH:$brew_bin" create-dmg 'gw.app' || true
-          ls
-          mv gw\ undefined.dmg gw_macos_${{ matrix.arch }}.dmg
-          ls
-          pwd
-
-      - name: upload
-        uses: actions/upload-artifact@v3
-        with:
-          name: gw_macos_${{ matrix.arch }}
-          path: ./*.dmg
+  #  macos-package:
+  #
+  #    runs-on: ${{ matrix.os }}
+  #    strategy:
+  #      matrix:
+  #        os: [ macos-13 ]
+  #        include:
+  #          - os: macos-13
+  #            arch: intel
+  #          - os: macos-13
+  #            arch: m1
+  #
+  #    steps:
+  #      - uses: actions/checkout@v3
+  #
+  #      - name: Install dependencies
+  #        run: |
+  #          brew install imagemagick graphicsmagick dylibbundler glfw fontconfig
+  #          brew list | grep python@
+  #
+  #          /opt/homebrew/opt/python@3.13/bin/python3.13 -m venv py_venv
+  #          source py_venv/bin/activate
+  #
+  #          python -m pip install --upgrade pip
+  #          python -m pip install packaging
+  #
+  #          npm install --global create-dmg
+  #
+  #          which python && python --version
+  #          which python3 && python3 --version
+  #
+  #      - name: Build and install htslib with libdeflate
+  #        run: |
+  #
+  #          wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.20/htslib-1.20.tar.bz2
+  #          tar -xvf htslib.tar.bz2 && mv htslib-* htslib && rm htslib.tar.bz2
+  #
+  #          git clone --depth 1 https://github.com/ebiggers/libdeflate.git
+  #          cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build
+  #          cp build/libdeflate.a ../htslib
+  #          cp libdeflate.h ../htslib
+  #          ls ../htslib
+  #
+  #          cd ../htslib
+  #          LDFLAGS="$LDFLAGS -L./" CPPFLAGS="$CPPFLAGS -I./" ./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
+  #          make
+  #          sudo make install
+  #
+  #      - name: Make Prep
+  #        run: |
+  #          make prep
+  #
+  #      - name: package
+  #        run: |
+  #
+  #          osacompile -o gw.app deps/gw_applescript_prog.txt
+  #          cp deps/gw_droplet.icns gw.app/Contents/Resources/droplet.icns
+  #
+  #          echo "BUILDING GW"
+  #
+  #          brew_lib=$(brew --prefix)/lib
+  #          brew_include=$(brew --prefix)/include
+  #          brew_bin=$(brew --prefix)/bin
+  #
+  #          LDFLAGS="${LDFLAGS} -L${brew_lib}" CPPFLAGS="${CPPFLAGS} -I${brew_include}" make
+  #
+  #          mv gw ./gw.app/Contents/MacOS
+  #          rm -rf include lib src Makefile
+  #
+  #          PATH="$PATH:$brew_bin" dylibbundler -od -b -x ./gw.app/Contents/MacOS/gw -d ./gw.app/Contents/libs/ -p @executable_path/../libs/
+  #
+  #          echo "VALIDATION"
+  #          otool -L gw.app/Contents/MacOS/gw
+  #          echo ""
+  #
+  #          echo "CODE SIGNING"
+  #          ls -l
+  #          sudo chown -R $(whoami) ./gw.app
+  #          chmod -R a+rw ./gw.app
+  #          sudo codesign --remove-signature ./gw.app
+  #          sudo codesign --force --deep -s - gw.app -v
+  #          sudo codesign --verify -vvvv gw.app
+  #
+  #          PATH="$PATH:$brew_bin" create-dmg 'gw.app' || true
+  #          ls
+  #          mv gw\ undefined.dmg gw_macos_${{ matrix.arch }}.dmg
+  #          ls
+  #          pwd
+  #
+  #      - name: upload
+  #        uses: actions/upload-artifact@v3
+  #        with:
+  #          name: gw_macos_${{ matrix.arch }}
+  #          path: ./*.dmg
 
   deb-package:
     runs-on: ubuntu-22.04
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
       - name: Install dependencies
         run: |
           sudo apt update
@@ -182,8 +182,6 @@ jobs:
           sed -i 's@-L/usr/local/lib@-L/usr/local/lib -L/usr/lib/gwhts@g' Makefile
 
           make prep
-          make
-          cp gw usr/bin
 
           cp include/gw_icon.png usr/share/icons/
           cp include/gw_icon.png usr/share/icons/hicolor/512x512/apps/
@@ -193,7 +191,7 @@ jobs:
         run: |
           dh_make --single --createorig --packagename gw_${version} --email clealk@cardiff.ac.uk --yes --native
 
-          printf "usr/bin/gw\nusr/share/icons/gw_icon.png\nusr/share/applications/gw.desktop\nusr/lib/gwhts/\nusr/lib/x86_64-linux-gnu/libglfw.so.3\nusr/lib/x86_64-linux-gnu/libglfw.so.3.3" > debian/install
+          printf "usr/bin/gw\nusr/share/icons/gw_icon.png\nusr/share/applications/gw.desktop\nusr/lib/gwhts/\nusr/lib/x86_64-linux-gnu/libglfw.so.3\nusr/lib/x86_64-linux-gnu/libglfw.so.3.4" > debian/install
 
           export LDFLAGS="$LDFLAGS -L./lib/skia/out/Release-x64 -L/usr/local/lib -L/usr/lib -L./usr/lib/gwhts -Wl,-rpath,'$ORIGIN/../lib/gwhts'"
 
@@ -210,7 +208,7 @@ jobs:
           dpkg-buildpackage -us -uc
 
       - name: upload
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: debian-package
           path: /home/runner/work/gw/*.deb
